version: '3.3'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        - PASSWORD=YourPassword
    ports:
      - "3001:3001"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
